sudo docker exec mininet-4001 service ssh restart
sudo docker exec mininet-4002 service ssh restart
sudo docker exec mininet-4003 service ssh restart
sudo docker exec mininet-4004 service ssh restart
sudo docker exec mininet-4005 service ssh restart
sudo docker exec mininet-4006 service ssh restart
sudo docker exec mininet-4007 service ssh restart
sudo docker exec mininet-4008 service ssh restart
sudo docker exec mininet-4009 service ssh restart
sudo docker exec mininet-4010 service ssh restart
sudo docker exec mininet-4011 service ssh restart
sudo docker exec mininet-4012 service ssh restart
sudo docker exec mininet-4013 service ssh restart
sudo docker exec mininet-4014 service ssh restart
sudo docker exec mininet-4015 service ssh restart
sudo docker exec mininet-4016 service ssh restart
